name: Setup Python Dependencies
description: Install JoinMarket NG Python dependencies with caching

inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.14'
  components:
    description: Comma-separated list of components to install (e.g., jmcore,jmwallet,maker)
    required: true
  install-dev:
    description: Install dev dependencies
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: |
          **/requirements*.txt
          **/pyproject.toml

    - name: Generate cache key
      id: cache-key
      shell: bash
      run: |
        # Replace commas with hyphens for cache key
        COMPONENTS_KEY=$(echo "${{ inputs.components }}" | tr ',' '-')
        echo "components-key=${COMPONENTS_KEY}" >> $GITHUB_OUTPUT

    - name: Cache installed packages
      uses: actions/cache@v5
      id: deps-cache
      with:
        path: |
          ~/.local
          /opt/hostedtoolcache/Python
        key: python-deps-${{ runner.os }}-${{ inputs.python-version }}-${{ steps.cache-key.outputs.components-key }}-${{ inputs.install-dev }}-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}

    - name: Install dependencies
      if: steps.deps-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        IFS=',' read -ra COMPONENTS <<< "${{ inputs.components }}"
        DEV_FLAG=""
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          DEV_FLAG="[dev]"
        fi

        for component in "${COMPONENTS[@]}"; do
          component=$(echo "$component" | xargs)  # trim whitespace
          echo "Installing $component..."
          pip install -e "${component}${DEV_FLAG}"
        done
